version: '3'
services:
  backend:
    build: .
    depends_on:
      - database
    ports:
      - "2500:2500"
    environment:
      # - name=${PORT}
      - PORT = 2500
      - MONGODB_CNN = mongodb://database/test
      
  database:
    image: mongo 
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'
